### ISSUE TITLE
looks like the default configuration is wrong

### ISSUE THREAD

**Issue by OskarStark** [sonata-project/SonataClassificationBundle#127]
hey guys, i don't have some issues, but this looks weird to me!

1) doc seems to be ok:
![bildschirmfoto 2015-08-18 um 15 40 36](https://cloud.githubusercontent.com/assets/995707/9331417/ade09e1e-45bf-11e5-8957-4b18b04608d0.png)

2) the command which displays the default config looks WEIRD:
![bildschirmfoto_2015-08-18_um_15_40_39](https://cloud.githubusercontent.com/assets/995707/9331422/ba02d838-45bf-11e5-8d55-e1860e9e715f.jpg)

what do you think @rande @Soullivaneuh

**Comment by Soullivaneuh** [comment]
I think your dumped configuration is right because [AdminController](https://github.com/sonata-project/SonataClassificationBundle/blob/master/Controller/CategoryAdminController.php) exists and is defined [here](https://github.com/sonata-project/SonataClassificationBundle/blob/master/DependencyInjection/Configuration.php#L52).

**Comment by OskarStark** [comment]
ok, but then the docs are wrong, right?

shall i provide a PR?

**Comment by Soullivaneuh** [comment]
I think so.

**Comment by OskarStark** [comment]
:smile: 

@rande what do you say?

**Comment by rande** [comment]
@OskarStark as you say, the documentation is wrong

**Comment by OskarStark** [comment]
done
