### ISSUE TITLE
 sonata-users › Classification bundle - Media bundle

### ISSUE THREAD

**Issue by martinfer** [sonata-project/SonataClassificationBundle#60]
Hi,

I´ve updated media bundle and had to add classification bundle because of the dependency. Since then I am getting this error when trying to batch load images.

c:\xampp183\php\php.exe "-c" "C:\xampp183\php\php.ini" app/console sonata:media:add-multiple --file=imagenesvinos-test.csv
 > 16150 - 100Pipers_ScotchWhisky.jpg
A managed+dirty entity default can not be scheduled for insertion. : ["sonata.media.provider.image","default","C:\
\xampp183\\htdocs\\ev2\\web\\bundles\\ev\\images\\vinos\\100Pipers_ScotchWhisky_ET.jpg"]
An exception occurred while executing 'INSERT INTO classification__context (name, enabled, created_at, updated_at,
 id) VALUES (?, ?, ?, ?, ?)' with params ["default", 1, "2014-10-17 11:14:56", "2014-10-17 11:14:56", "default"]:

SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'default' for key 'PRIMARY' : ["sonata.media
.provider.image","default","C:\\xampp183\\htdocs\\espaciovinov2\\web\\bundles\\evespaciovino\\images\\vinos\\135An
iversario_Blend.jpg"]

I´m not using classification bundle, how can I disable it so its not a required field in the media admin?

Thanks!

**Comment by lemoinem** [comment]
Hello,

In case someone hit the same issue again, I just hit the same error message. My problem was because I specified a provider that wasn't enabled for the given context.

**Comment by Soullivaneuh** [comment]
@martinfer Can you update your dependencies and try @lemoinem proposition?

**Comment by lemoinem** [comment]
The problem didn't come from the bad provider (fixing it did allow my fixtures to run, but once only).

They now crash again. I'm starting to think it's because I'm doing a flush/clear on my OM. The managed+dirty entity is a `Proxies\__CG__\Application\Sonata\ClassificationBundle\Entity\Context` (`Application\Sonata\ClassificationBundle` was generated using easy-extends).

I'm guessing the context is loaded from the DB at some point, cached and re-used later without being refreshed. I just can't find where in the code it is put in cache (It might be through a category or somewhere in the bridge between ClassificationBundle and MediaBundle).

**Comment by lemoinem** [comment]
Ok, as I suspected then problem was because related to caching the rootCategories through an ObjectManager#clear. I submitted a PR in MediaBundle directly.

@Soullivaneuh, could you have a look at the PR? You seem to have the commit on MediaBundle too...

**Comment by Soullivaneuh** [comment]
I'll follow it but I'm not sure to be able to handle it correctly.

**Comment by lemoinem** [comment]
In the mean time, for hte ones hitting this bug, You can use this service workaround:
https://gist.github.com/lemoinem/5497d46df74ac9a9df14

**Comment by chlabelek** [comment]
For some reason this happens only with phpunit.
I'm using version 4.8.9 because I'm with PHP 5.5, could not test with the latest version.
